# Generated by Django 3.0.5 on 2020-04-28 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCall', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apiKeys',
            new_name='apiKeysModel',
        ),
    ]
