# Generated by Django 3.0.5 on 2020-04-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCall', '0002_auto_20200428_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='youtubeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField()),
                ('description', models.TextField()),
                ('publish_datetime', models.DateField()),
                ('thumbnail_url', models.URLField(max_length=300)),
            ],
        ),
    ]
