# Generated by Django 3.0.5 on 2020-04-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCall', '0003_youtubemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubemodel',
            name='thumbnail_url',
            field=models.TextField(),
        ),
    ]
